# only used for database dependency
version: '3'

services:
  att_database:
    image: mysql:5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance
    ports:
      - '52000:3306'
    networks:
      - att_bridge
networks:
  att_bridge:
    external: true
