# only used for database dependency
version: '3'

services:
  attendance_database:
    image: mysql:5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance
    ports:
      - '3306:3306'
